### ISSUE TITLE
Cannot get requirements

### ISSUE THREAD

**Issue by dbrody2004** [computerpencils/ScraXBRL#1]
When running pip install -r requirements.txt, the following shows up in the log -

URLs to search for versions for Twisted-Web==13.2.0 (from -r requirements.txt (line 4)):
  * https://pypi.python.org/simple/Twisted-Web/13.2.0
  * https://pypi.python.org/simple/Twisted-Web/
  Getting page https://pypi.python.org/simple/Twisted-Web/13.2.0
  Could not fetch URL https://pypi.python.org/simple/Twisted-Web/13.2.0: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/Twisted-Web/13.2.0 when looking for download links for Twisted-Web==13.2.0 (from -r requirements.txt (line 4))
  Getting page https://pypi.python.org/simple/Twisted-Web/
  Could not fetch URL https://pypi.python.org/simple/Twisted-Web/: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/Twisted-Web/ when looking for download links for Twisted-Web==13.2.0 (from -r requirements.txt (line 4))
  Could not find any downloads that satisfy the requirement Twisted-Web==13.2.0 (from -r requirements.txt (line 4))

**Comment by computerpencils** [comment]
Please refer to this page and install for your operating system: http://twistedmatrix.com/trac/

**Comment by dbrody2004** [comment]
Thanks. Was not able to install via pip but got it installed via apt-get along with some other dependencies.
